package LibrarySystem;

import java.util.Arrays;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jurijs
 */
public class FormRegister extends javax.swing.JFrame {

    /**
     * Creates new form FormRegister
     */
    public FormRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        regNameTextField = new javax.swing.JTextField();
        regLastNameTextField = new javax.swing.JTextField();
        regUserIdTextField = new javax.swing.JTextField();
        regPositionComboBox = new javax.swing.JComboBox();
        regButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        regPasswordField = new javax.swing.JPasswordField();
        regPasswordFieldConfirm = new javax.swing.JPasswordField();
        backButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name:");

        jLabel2.setText("Lastname:");

        jLabel3.setText("User ID:");

        jLabel4.setText("Password:");

        jLabel5.setText("Confirm Password:");

        jLabel6.setText("Position:");

        regNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regNameTextFieldActionPerformed(evt);
            }
        });

        regPositionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "student", "librarian", "administrator" }));
        regPositionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regPositionComboBoxActionPerformed(evt);
            }
        });

        regButton.setText("Register");
        regButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear All");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel7.setText("Registration");

        regPasswordFieldConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regPasswordFieldConfirmActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.setPreferredSize(new java.awt.Dimension(100, 29));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(clearButton)
                        .addGap(18, 18, 18)
                        .addComponent(regButton)
                        .addGap(18, 18, 18)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(regNameTextField)
                            .addComponent(regLastNameTextField)
                            .addComponent(regUserIdTextField)
                            .addComponent(regPositionComboBox, 0, 200, Short.MAX_VALUE)
                            .addComponent(regPasswordField)
                            .addComponent(regPasswordFieldConfirm)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(regNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(regLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(regUserIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(regPositionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(regPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(regPasswordFieldConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regButton)
                    .addComponent(clearButton)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regNameTextFieldActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        regLastNameTextField.setText(null);
        regNameTextField.setText(null);
        regPasswordField.setText(null);
        regPasswordFieldConfirm.setText(null);
        regUserIdTextField.setText(null);

// TODO add your handling code here:
    }//GEN-LAST:event_clearButtonActionPerformed

    private void regPositionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regPositionComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regPositionComboBoxActionPerformed

    private void regButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regButtonActionPerformed
        //Submit Button Code

        if (!regNameTextField.getText().equals("") && !regLastNameTextField.getText().equals("") && !regUserIdTextField.getText().equals("")
                && !regPasswordField.getPassword().equals("") && !regPasswordFieldConfirm.getPassword().equals("")) {

            String userName = regNameTextField.getText();
            String userLName = regLastNameTextField.getText();
            long userId = Long.parseLong(regUserIdTextField.getText());
            char[] password = regPasswordField.getPassword();
            char[] passwordConfirm = regPasswordFieldConfirm.getPassword();
            String userPosition = regPositionComboBox.getSelectedItem().toString();
            
           
            
            boolean confirmedUN = validateUserId(userId);
            if (!confirmedUN) {
                JOptionPane.showMessageDialog(this,
                        "Somebody already has this userID.",
                        "Invalid UserID",
                        JOptionPane.ERROR_MESSAGE);
            }
            boolean confirmedPW = validatePassword(password, passwordConfirm);
            if (confirmedPW && confirmedUN) {
                //SQL Insert
                DBManager dbm = new DBManager(userName, userLName, userId, password, userPosition);
                boolean success = dbm.register();
                if (success) {
                    System.out.println("Registration Successful");
                    //Register Button Code
                    this.setVisible(false);
//                //Register jFrame
//                FormLogin formLogin = new FormLogin();
//                formLogin.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Registration Failed.",
                            "Registration Failed",
                            JOptionPane.ERROR_MESSAGE);
                    System.out.println("Registration Failed");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Fill all fields",
                    "Registration Failed",
                    JOptionPane.ERROR_MESSAGE);
            System.out.println("Registration Failed");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_regButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        //Register Button Code
        this.setVisible(false);
        //Register jFrame
        FormLogin formLogin = new FormLogin();
        formLogin.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void regPasswordFieldConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regPasswordFieldConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regPasswordFieldConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegister().setVisible(true);
            }
        });
        
        
    }

    private Boolean validateUserId(long userId) {
        DBManager dbm = new DBManager(userId);
        if (!dbm.validateUserId()) { //False - Username Exists
            return false;
        }
        return true;
    }

    
    
    private Boolean validatePassword(char[] password, char[] passwordConfirm) {
        if (!Arrays.equals(password, passwordConfirm)) {
            JOptionPane.showMessageDialog(this,
                    "Passwords don't match.",
                    "Invalid Password",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if ((password.length < 6) || (password.length == 0)) {
            JOptionPane.showMessageDialog(this,
                    "Password is less than 6 characters or blank.",
                    "Invalid Password",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton backButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton regButton;
    private javax.swing.JTextField regLastNameTextField;
    private javax.swing.JTextField regNameTextField;
    private javax.swing.JPasswordField regPasswordField;
    private javax.swing.JPasswordField regPasswordFieldConfirm;
    private javax.swing.JComboBox regPositionComboBox;
    private javax.swing.JTextField regUserIdTextField;
    // End of variables declaration//GEN-END:variables
}
